name: CICD

on:
  push:
    branches: [ "main" ] # Triggered when code is pushed to the main branch
  pull_request:
    branches: [ "main" ] # Triggered when a pull request is created to the main branch

jobs:

  build:
    runs-on: ${{matrix.os}} # Set operating system with parameter
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macOS-latest] # Descript matrix.os content
    steps:
    - uses: actions/checkout@v3 # Clone the code

    - name: Set up Go
      uses: actions/setup-go@v4 # Set up Go enviroment
      with:
        go-version: '1.20' # Specify version

    - name: Build
      run: go build -v ./... 

    - name: Test 
      run: go test -v ./...

  image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PWD}}
      -
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: diverwil1995/scrape-demo:latest